# Cosmos DB Config
spring.data.mongodb.uri=${COSMOS_CONNECTION_STRING}

# Event Hub Config
spring.cloud.azure.eventhubs.connection-string=${EVENT_HUB_CONNECTION_STRING}
spring.cloud.azure.eventhubs.namespace=${EVENT_HUB_NAMESPACE}
spring.cloud.azure.eventhubs.event-hub-name=${EVENT_HUB_NAME}

# Transaction Config
transaction.code.get=${TRANSACTION_CODE_GET:002}
transaction.code.save=${TRANSACTION_CODE_POST:102}
transaction.code.update=${TRANSACTION_CODE_PUT:202}
transaction.code.delete=${TRANSACTION_CODE_DELETE:302}

# Logging Config
logging.level.com.azure=WARN

# Security Config
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AD_URI}