# Cosmos DB Config
spring.data.mongodb.uri=${COSMOS-CONNECTION-STRING}

# Event Hub Config
spring.cloud.azure.eventhubs.connection-string=${EVENT-HUB-CONNECTION-STRING}
spring.cloud.azure.eventhubs.namespace=${EVENT-HUB-NAMESPACE:training-azure-beth}
spring.cloud.azure.eventhubs.event-hub-name=${EVENT-HUB_NAME:customer-trace}

# Transaction Config
transaction.code.get=${TRANSACTION_CODE_GET:002}
transaction.code.save=${TRANSACTION_CODE_POST:102}
transaction.code.update=${TRANSACTION_CODE_PUT:202}
transaction.code.delete=${TRANSACTION_CODE_DELETE:302}

# Logging Config
logging.level.com.azure=WARN

# Security Config
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AD-URI}

# Azure Key Vault Config
spring.cloud.azure.keyvault.enabled=true
spring.cloud.azure.keyvault.secret.endpoint=https://training-azure-beth.vault.azure.net/