# Cosmos DB Config
spring.data.mongodb.database=${COSMOS_DB_DATABASE}
spring.data.mongodb.uri=${COSMOS_DB_URI}
spring.data.mongodb.username=${COSMOS_DB_USERNAME}
spring.data.mongodb.password=${COSMOS_DB_PASSWORD}

# Event Hub Config
#spring.cloud.stream.


